#!/bin/sh

#only run GJF pre-commit if Java files have changed

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.java$") || true)
if [ ! -z "${files}" ]; then
    comma_files=$(echo "$files" | paste -s -d "," -)
    echo "$comma_files"
    java -jar "${REPO_ROOT_DIR}/config/java/google-java-format-1.7-all-deps.jar" -a -r "$comma_files"
    git add $(echo "$files" | paste -s -d " " -)
fi